# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-10-18 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201018_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.CharField(max_length=32, null=True, verbose_name='个人介绍'),
        ),
    ]
