# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-10-18 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_user_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(default='like read', max_length=32, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.CharField(max_length=32, null=True, verbose_name='个人爱好'),
        ),
    ]
